services:
  node3:
    build:
      context: ./.docker/mongo
    env_file:
        - .env
    container_name: node3.${HOST_NAME}
    hostname: node3.${HOST_NAME}
    restart: unless-stopped
    volumes:
      - ./.docker/mongo-files/data:/data/db
      - ./key:/opt/keyfile
    ports:
      - "${NODE3_EXTERNAL_PORT}:${NODE3_INTERNAL_PORT}"
    command: mongod --keyFile /opt/keyfile/mongodb-keyfile --replSet ${REPLICA_SET_NAME} --bind_ip localhost,node3.${HOST_NAME}
networks:
  default:
    name:
      net_${ENV}_${SUFFIX}