services:
  node2:
    build:
      context: ./.docker/mongo
    env_file:
        - .env
    container_name: node2.${HOST_NAME}
    hostname: node2.${HOST_NAME}
    restart: unless-stopped
    volumes:
      - ./.docker/mongo-files/data:/data/db
      - ./key:/opt/keyfile
    ports:
      - "${NODE2_EXTERNAL_PORT}:${NODE2_INTERNAL_PORT}"
    command: mongod --keyFile /opt/keyfile/mongodb-keyfile --replSet ${REPLICA_SET_NAME} --bind_ip localhost,node2.${HOST_NAME}
networks:
  default:
    name:
      net_${ENV}_${SUFFIX}