services:
  node1:
    build:
      context: ./.docker/mongo
    env_file:
        - .env
    container_name: node1.${HOST_NAME}
    hostname: node1.${HOST_NAME}
    restart: unless-stopped
    volumes:
      - ./.docker/mongo-files/data:/data/db
      - ./key:/opt/keyfile
    ports:
      - "${NODE1_EXTERNAL_PORT}:${NODE1_INTERNAL_PORT}"
    command: mongod --keyFile /opt/keyfile/mongodb-keyfile --replSet ${REPLICA_SET_NAME} --bind_ip localhost,node1.${HOST_NAME}
    # command: mongod
networks:
  default:
    name:
      net_${ENV}_${SUFFIX}